config/routes.rb
Rails.application.routes.draw do



  #to make the start page is the courses
  root to: 'courses#index'

  resources :lectures do
    member do
      put "like"=>"lectures#upvote"
      put "dislike"=>"lectures#downvote"
    end
    resource :comments
  end
  resources :courses
  # resources :courses do
  #   resources :lectures
  # end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :lecture
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :user
  has_many :lectures

end

app/models/lecture.rb
class Lecture < ApplicationRecord
  acts_as_votable
  mount_uploader :attachment, FileUploader
  belongs_to :user
  belongs_to :course
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_voter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #for gender
  enum gender: {"Prefer not to choose": 0, Male: 1, Female: 2}

  #for avatar
  mount_uploader :avatar, AvatarUploader

  validates_presence_of :avatar
  validates_integrity_of :avatar
  validates_processing_of :avatar
  has_many :courses
  has_many :lectures

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :date_of_birth, :gender, :avatar, :avatar_cache, :remove_avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :date_of_birth, :gender, :avatar, :avatar_cache, :remove_avatar])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @lecture = Lecture.find(params[:lecture_id])

    @comment = @lecture.comments.new(comment_params)
    @comment.save
    redirect_to lecture_path(@lecture)

    end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:title,:user_id)
    end
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  before_action :set_lecture, only: [:show, :edit, :update, :destroy , :upvote , :downvote ]
  before_action :get_course, only: [:edit, :new]
  # GET /lectures
  # GET /lectures.json
  def index
    @lectures = Lecture.all
  end

  # GET /lectures/1
  # GET /lectures/1.json
  def show
  end

  # GET /lectures/new
  def new
    @lecture = Lecture.new
  end

  # GET /lectures/1/edit
  def edit
  end

  # POST /lectures
  # POST /lectures.json
  def create
    @lecture = Lecture.new(lecture_params)

    respond_to do |format|
      if @lecture.save
        format.html { redirect_to @lecture, notice: 'Lecture was successfully created.' }
        format.json { render :show, status: :created, location: @lecture }
      else
        format.html { render :new }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lectures/1
  # PATCH/PUT /lectures/1.json
  def update
    respond_to do |format|
      if @lecture.update(lecture_params)
        format.html { redirect_to @lecture, notice: 'Lecture was successfully updated.' }
        format.json { render :show, status: :ok, location: @lecture }
      else
        format.html { render :edit }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lectures/1
  # DELETE /lectures/1.json
  def destroy
    @lecture.destroy
    respond_to do |format|
      format.html { redirect_to lectures_url, notice: 'Lecture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def upvote
    @lecture.upvote_from current_user
    redirect_to lecture_path
  end
  def downvote
    @lecture.downvote_from current_user
    redirect_to lecture_path
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lecture
      @lecture = Lecture.find(params[:id])
    end

  def get_course
    @courses_created_by_current_user = Course.where(:user_id=>current_user.id)
  end


    # Never trust parameters from the scary internet, only allow the white list through.
    def lecture_params
      # params.fetch(:lecture, {})
      params.require(:lecture).permit(:attachment,:content,:user_id,:course_id)

    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :course_title %>
  </div>
  <!--for add current user id -->
  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.title %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @course.title %>
</p>


<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyOnRailsProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lectures/_form.html.erb
<%= form_with(model: lecture, local: true) do |form| %>
  <% if lecture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2>

      <ul>
        <% lecture.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, :class => 'ckeditor'%>
  </div>

  <div class="field">
    <%= form.label :attachment %>
    <%= form.file_field :attachment %>
  </div>

  <!--for add current user id -->
  <%= form.hidden_field :user_id, value: current_user.id %>

  <!--for add current course id -->
  <div class="field">
    <%= form.label :Course %>
    <%= form.collection_select :course_id, @courses_created_by_current_user, :id, :title, include_blank: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lectures/edit.html.erb
<h1>Editing Lecture</h1>

<%= render 'form', lecture: @lecture %>

<%= link_to 'Show', @lecture %> |
<%= link_to 'Back', lectures_path %>

app/views/lectures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lectures</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lectures.each do |lecture| %>
      <tr>
        <td><%= link_to 'Show', lecture %></td>
        <td><%= link_to 'Edit', edit_lecture_path(lecture) %></td>
        <td><%= link_to 'Destroy', lecture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lecture', new_lecture_path %>

app/views/lectures/new.html.erb
<h1>New Lecture</h1>

<%= render 'form', lecture: @lecture %>

app/views/lectures/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Content:</strong>
  <%= raw @lecture.content %>
</p>
<p>
  <strong>attachment:</strong>
  <a href="<%= @lecture.attachment %>"> Download the attachment</a>
</p>


<%= link_to like_lecture_path(@lecture), class: "like", method: :put do %>
  <button type="button" class="btn btn-info" aria-label="left Align">
    <span class="glyphicon glyphicon-thumbs-up glyphicom-align-center" aria-hidden="true">Like</span>
    <span class="badge"><%= @lecture.get_upvotes.size %></span>
  </button>
<% end %>

<%= link_to dislike_lecture_path(@lecture), class: "dislike", method: :put do %>
  <button type="button" class="btn btn-info" aria-label="left Align">
    <span class="glyphicon glyphicon-thumbs-down glyphicom-align-center" aria-hidden="true">Dislike</span>
    <span class="badge"><%= @lecture.get_downvotes.size %></span>
  </button>
<% end %>
<br/><br/>
<table>
  <thead>
  <tr>
    <th>Comments</th>
    <!--    <th>user</th>-->
  </tr>

  </thead>

  <tbody>
  <% @lecture.comments.each do |comment| %>

    <tr>
      <td><%= comment.body %></td>
      <!--    <td><%#= comment.user.email%></td>-->
    </tr>
  <% end %>
  </tbody>
</table>


<%= form_for([@lecture, @lecture.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :Write_comment %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>

  </div>

<% end %>
<%= link_to 'Edit', edit_lecture_path(@lecture) %> |
<%= link_to 'Back', lectures_path %>